name: CI Build and Test

on:
  push:
    branches: [ main, next, '+([0-9])\.+([0-9])\.x-maintenance' ]
  pull_request:
    branches: [ main, next, '+([0-9])\.+([0-9])\.x-maintenance' ]


env:
  SYSROOT_PATH: ${{ github.workspace }}/deps_install

jobs:
  setup_deps:
    runs-on: ubuntu-latest
    outputs:
      deps_cache_key: ${{ steps.cache-key.outputs.hash }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Dependency Hash Key
        id: cache-key
        run: echo "hash=$(sha256sum .deps | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Restore Dependency Cache
        uses: actions/cache@v4
        id: cache-restore
        with:
          path: ${{ env.SYSROOT_PATH }}
          key: ${{ runner.os }}-deps-${{ steps.cache-key.outputs.hash }}

      - name: Build and Install System-Dependencies
        if: false && steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          echo "Installing Boost..."
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
          echo "Copying Boost to SYSROOT..."
          mkdir -p ${{ env.SYSROOT_PATH }}/include/ ${{ env.SYSROOT_PATH }}/lib/
          sudo cp -r /usr/include/boost ${{ env.SYSROOT_PATH }}/include/
          sudo cp /usr/lib/x86_64-linux-gnu/libboost_* ${{ env.SYSROOT_PATH }}/lib/

      - name: Build and Install Project Dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          echo "Building dependencies..."
          mkdir -p ${{ env.SYSROOT_PATH }}
          ./.github/scripts/install-deps.sh "${{ env.SYSROOT_PATH }}"
          echo "Dependencies built and installed to ${{ env.SYSROOT_PATH }}"

      - name: Cache Save Confirmation
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: echo "New dependency cache will be saved."

  build_project:
    needs: setup_deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Dependency Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.SYSROOT_PATH }}
          key: ${{ runner.os }}-deps-${{ needs.setup_deps.outputs.deps_cache_key }}

      - name: Build and Install Boost
        run: |
          echo "Installing Boost..."
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DSYSROOT_PATH=${{ env.SYSROOT_PATH }}

      - name: Build Project
        run: cmake --build build

      # - name: Run Tests
      #   run: cmake --build build --target check
