name: CI Build and Test

on:
  push:
    branches: [ main, next, '+([0-9])\.+([0-9])\.x-maintenance' ]
  pull_request:
    branches: [ main, next, '+([0-9])\.+([0-9])\.x-maintenance' ]

env:
  SYSROOT_PATH: /opt/sysroot

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/Dockerfile
          build-args: |
            SYSROOT_PATH=${{ env.SYSROOT_PATH }}
          tags: firebolt-native-transport-ci:latest
          push: false
          outputs: type=docker,dest=/tmp/ci-image.tar
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: ci-image
          path: /tmp/ci-image.tar

  format_check:
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: ci-image
          path: /tmp

      - name: Load Docker Image
        run: docker load --input /tmp/ci-image.tar

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run clang-format check
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace firebolt-native-transport-ci:latest \
            bash -c "git ls-files -- '*.cpp' '*.h' | xargs clang-format --dry-run --Werror"

  build_project:
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: ci-image
          path: /tmp

      - name: Load Docker Image
        run: docker load --input /tmp/ci-image.tar

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        run: |
          VERSION=$(git describe --tags --dirty --match "v[0-9]*")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version: $VERSION"

      - name: Configure, Build and Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace firebolt-native-transport-ci:latest \
            bash -c "cmake -B build \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX:PATH=\"${{ env.SYSROOT_PATH }}/usr\" \
              -DSYSROOT_PATH=${{ env.SYSROOT_PATH }} \
              -DENABLE_TESTS=ON -DDISCOVER_UT=ON && \
            cmake --build build && \
            ctest --test-dir build/test"

      - name: Make Release package of Transport sources
        run: |
          ./.github/scripts/mk-release-package.sh \
            --version ${{ env.VERSION }} \
            --package firebolt-native-transport \
            --dst ${{ github.workspace }}/release

      - name: Upload Transport package as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ${{ github.workspace }}/release
